setwd("C:/Users/Nathan/Downloads/macro 4")
library(readxl)
library(writexl)
library(dfms)
library(xtable)

cboe<-read_excel("CBOE Brazil ETF Volatility Index.xls")
msci<-read_excel("msci emerging markets.xlsx")
oil<-read_excel("oil price.xls")
peso<-read_excel("peso exg rate.xlsx")
real<-read_excel("brl exchange.xlsx")
bills<-read_excel("mexico bills.xlsx")
commodity<-read_excel("commodity index.xlsx")
bex<-read_excel("BEX_Indices_20230703.xlsx", sheet = excel_sheets("BEX_Indices_20230703.xlsx")[2])
